# Generated by Django 3.1.3 on 2023-07-07 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mipyme',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('productos', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.PositiveBigIntegerField(default=0)),
                ('mipyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp.mipyme')),
            ],
        ),
    ]
