# Generated by Django 3.1.3 on 2023-07-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipyme',
            name='num',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
