# Generated by Django 3.1.3 on 2023-08-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_auto_20230721_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipyme',
            name='valido',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
