# Generated by Django 3.1.3 on 2023-08-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0004_mipyme_valido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipyme',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
