# Generated by Django 3.1.3 on 2023-08-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0006_auto_20230808_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipyme',
            name='imagen',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
