# Generated by Django 3.1.3 on 2023-08-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0007_mipyme_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipyme',
            name='direccion',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
