# Generated by Django 3.1.3 on 2023-08-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0008_mipyme_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mipyme',
            old_name='direccion',
            new_name='provincia',
        ),
    ]
