# Generated by Django 3.1.3 on 2023-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0009_auto_20230816_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipyme',
            name='productos',
            field=models.CharField(max_length=100),
        ),
    ]
