# Generated by Django 3.1.3 on 2023-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0013_auto_20230915_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipyme',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
