# Generated by Django 3.1.3 on 2023-09-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0014_auto_20230915_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipyme',
            name='imagen',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
