# Generated by Django 3.1.3 on 2023-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0015_auto_20230915_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mipyme',
            name='num',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mipyme',
            name='provincia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
