# Generated by Django 3.1.3 on 2023-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0018_auto_20230915_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='mipyme',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
